# Generated by Django 4.2 on 2023-04-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eletronics',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250, verbose_name='')),
                ('main_category', models.CharField(default='', max_length=250, verbose_name='')),
                ('sub_category', models.CharField(default='', max_length=250, verbose_name='')),
                ('ratings', models.CharField(default='', max_length=250, verbose_name='')),
                ('no_of_ratings', models.CharField(default='', max_length=250, verbose_name='')),
                ('discount_price', models.CharField(default='', max_length=250, verbose_name='')),
                ('actual_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
                ('identity', models.CharField(default='customer', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('eletronics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.eletronics')),
            ],
        ),
    ]
