# Generated by Django 4.2 on 2023-04-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletronics',
            name='actual_price',
            field=models.CharField(default='', max_length=250, verbose_name=''),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('time', models.CharField(max_length=250)),
                ('eletronics', models.ManyToManyField(to='shop.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
        ),
    ]
